apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  namespace: ticketing-app
  labels:
    app: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
      - name: hotel-service
        image: malikvti/hotel-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
        env:
        - name: DB_SERVER
          valueFrom:
            secretKeyRef:
              name: ticketing-secrets
              key: DB_SERVER
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: ticketing-secrets
              key: DB_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: ticketing-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ticketing-secrets
              key: DB_PASSWORD
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: ticketing-secrets
              key: DB_PORT
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
  namespace: ticketing-app
  labels:
    app: hotel-service
spec:
  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: http
  selector:
    app: hotel-service
