apiVersion: v1
kind: Secret
metadata:
  name: ticketing-secrets
  namespace: ticketing-app
type: Opaque
stringData:
  DB_SERVER: "10.100.33.68"
  DB_DATABASE: "ticketing_app"
  DB_USER: "lek"
  DB_PASSWORD: "P@ssw0rd"
  DB_PORT: "1433"
  JWT_SECRET_KEY: "bGZiXRX7b3FPCzLWkfRLiUtrQ+lknCeKMtSF9+oJKNI="
